baseURL = "/"
languageCode = "en-us"
title = "Kagome"
theme = "kagome"
paginate = 7
copyright = "Â© 2021 <a href=\"https://sukoshi.xyz\">Sukoshi</a>."
hasCJKLanguage = true

[privacy]
  [privacy.disqus]
    disable = true
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# ä½œè€…ä¿¡æ¯
[author]
  name = "Sukoshi"
  email = "guanquanhong@163.com"
  description = "æ¢…èŠ±é¹¿çš„è§’å«é¹¿è§’"
  avatar = "https://s.gravatar.com/avatar/7b5a0b07a98895278cfa862b1f32ae8f?s=200&r=g&d=retro"

# èœå•/å¯¼èˆªæ 
[menu]
  # é¡¶éƒ¨å¯¼èˆªæ 
  [[menu.main]]
    identifier = "/"
    name = "ğŸ  HOME"
    title = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/docs"
    name = "ğŸ—‚ï¸ DOCS"
    title = "DOCS"
    url = "/docs"
    weight = 2
  [[menu.main]]
    identifier = "/about"
    name = "ğŸ˜ˆ ABOUT"
    title = "ABOUT"
    url = "/about"
    weight = 3
  
  # åº•éƒ¨ç¤¾äº¤å›¾æ ‡
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/miiiku"
    weight = 1
  [[menu.social]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/guanquanhong"
    weight = 2
  [[menu.social]]
    identifier = "instagram"
    name = "instagram"
    url = "https://www.instagram.com/sukoshi_dayo/"
    weight = 3
  [[menu.social]]
    identifier = "weibo"
    name = "weibo"
    url = "https://weibo.com/u/5561168966"
    weight = 4
  [[menu.social]]
    identifier = "zhihu"
    name = "zhihu"
    url = "https://www.zhihu.com/people/miku-84"
    weight = 5

# ä¸»é¢˜ç›¸å…³é…ç½®é¡¹
[params]
  keywords = ["hugo", "theme", "kikyo", "kagome", "ä¸ªäººåšå®¢", "ä¸»é¢˜"]
  description = "Hugoä¸»é¢˜Kagomeæ¼”ç¤ºç«™ç‚¹"
  mainSections = ["posts"]
  toc_show_len = 300

  [params.analytics]
    baidu = "ce6f52295ca4633af0237491d4810283"

  [params.widget]
    articles_count = 6
    categories_count = 6
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
